### ISSUE TITLE
Bureau Connection - Error executing run queue item 

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#29]
We got our server working and everything is running just fine. 

However, 
We are trying to get parlor games working in our Whirled instance (AVRG games work just fine). Whenever we try and load a parlor game, it comes out an exception.
Here is a picture:
![image](https://cloud.githubusercontent.com/assets/9708050/21460964/3f20502e-c902-11e6-8be1-1a0f0b4cc221.png)

Whenever we click the "Create" button in a parlor game table, here is what's thrown on the msoy-server console:

`2016-12-22 11:53:10,137 INFO Logger: Session initiated [type=GameAuthName, who=mist.bhusal@gmail.com, conn=[id=664, addr=/173.172.155.95]]
2016-12-22 11:53:10,573 WARN Logger: Failed to create manager for game [config=[type=data.ParlorGameConfig, game=[gameId=2577, name=Seed Dealer, description=Uh oh! Hamtaro is out of sunflower seeds, and he is really HUNGRY! Boss has plenty of seeds for you! Use your mouse to pick them up! Don't let them spoil!, avrGame=false, thumbMedia=efb952262e5470a1ca53d0bdfbbdfc88cf972fa0.png, creatorId=345], groupId=472, splashMedia=null, params={}, players=(Shadowsych), rated=true, ais=()]]
java.lang.NoSuchFieldError: BUREAU_ACCESS_PLACE
	at com.whirled.game.server.WhirledGameManager.getAccessController(WhirledGameManager.java:157)
	at com.threerings.crowd.server.PlaceManager.startup(PlaceManager.java:278)
	at com.threerings.crowd.server.PlaceRegistry.createPlace(PlaceRegistry.java:222)
	at com.threerings.crowd.server.PlaceRegistry.createPlace(PlaceRegistry.java:112)
	at com.threerings.msoy.game.server.LobbyManager.createGameManager(LobbyManager.java:253)
	at com.threerings.msoy.game.server.MsoyTableManager.createGameManager(MsoyTableManager.java:87)
	at com.threerings.parlor.server.TableManager.createGame(TableManager.java:437)
	at com.threerings.parlor.server.TableManager.createTable(TableManager.java:189)
	at com.threerings.msoy.game.server.LobbyManager.playNowSingle(LobbyManager.java:180)
	at com.threerings.msoy.game.server.GameGameRegistry.finishPlayNow(GameGameRegistry.java:961)
	at com.threerings.msoy.game.server.GameGameRegistry$14.requestProcessed(GameGameRegistry.java:845)
	at com.threerings.presents.util.ResultListenerList.requestProcessed(ResultListenerList.java:39)
	at com.threerings.msoy.game.server.GameGameRegistry$13.handleSuccess(GameGameRegistry.java:796)
	at com.samskivert.jdbc.RepositoryUnit.handleResult(RepositoryUnit.java:57)
	at com.samskivert.util.Invoker$Unit.run(Invoker.java:81)
	at com.threerings.presents.server.PresentsDObjectMgr.processUnit(PresentsDObjectMgr.java:672)
	at com.threerings.presents.server.PresentsDObjectMgr.run(PresentsDObjectMgr.java:405)
	at com.threerings.presents.server.PresentsServer.run(PresentsServer.java:244)
	at com.threerings.presents.server.PresentsServer.runServer(PresentsServer.java:141)
	at com.threerings.msoy.server.MsoyServer.main(MsoyServer.java:157)
2016-12-22 11:53:10,573 WARN Logger: Failed to create play now table [who=mist.bhusal@gmail.com (pid=2 oid=959), error=m.internal_error].
2016-12-22 11:53:12,470 INFO Logger: Puddle#1: 30s tick occured 
2016-12-22 11:53:12,500 WARN Logger: Invocation listener never responded to: server.InvocationManager$1, methodId=1
2016-12-22 11:53:14,857 INFO Logger: Shutting down lobby [gameId=-2502]
2016-12-22 11:53:14,857 INFO Logger: No longer hosting game [gameId=-2502]`

How should we go about fixing this? 

We urgently need your help,
Pravat Bhusal.

**Comment by Shadowsych** [comment]
Mr. Bayne,

we desperately need your help for this. Please do respond.

**Comment by Shadowsych** [comment]
Still awaiting a reply, there's really no documentation to fix this.

**Comment by Shadowsych** [comment]
It's May 7th, and I'm still wondering if you can respond?
